vegaNode:
  nodeID: vm
  nodeType: Master
  nodeRoles: []
  nodeIPAddr: 127.0.0.1
  nodePort: 7770

vegaCluster:
  - nodeID: c1
    nodeType: Compute
    nodeRoles: [TxValidation, OutputStore]
    nodeIPAddr: 127.0.0.1
    nodePort: 7771

  - nodeID: c2
    nodeType: Compute
    nodeRoles: [TxValidation, OutputStore]
    nodeIPAddr: 127.0.0.1
    nodePort: 7772

bitcoinNetwork: bsv

logLevel: Debug

logFileName: ./debug.log

bitcoinNodeListenIP: 127.0.0.1

bitcoinNodeListenPort: 3000

endPointHTTPSListenIP: 127.0.0.1

endPointHTTPSListenPort: 9091

maxTxProcThreads: 80

maxBitcoinPeerCount: 10

unresponsivePeerConnTimeoutSecs: 180

acivatePeerDiscovery: True

staticPeerList: []

allegoryVendorSecretKey: 1435cf8e437d789eac332c3c66b2a51876e58c21db4b4da15488c3decb1a8b57

maxTMTBuilderThreads: 20

maxTMTQueueSize: 1024

txProcInputDependenciesWait: 240

txProcTimeoutSecs: 250

tlsCertificatePath: ./example.crt

tlsKeyfilePath: ./example.key

tlsCertificateStorePath: ./

neo4jUsername: neo4j

neo4jPassword: neo4j

allegoryNameUtxoSatoshis: 5555

allegoryTxFeeSatsProducerAction: 400

allegoryTxFeeSatsOwnerAction: 200

txOutputValuesCacheKeyBits: 20

unconfirmedTxCacheKeyBits: 16

shardingHashSecretSalt: 29347693

maxTxProcessingThreads: 100

maxTxProcessingBuffer: 100

 blocksFetchWindow: 4